"""stage8_servicenow_integration_schema

Revision ID: 28087f9366b3
Revises: aa751ab79fa1
Create Date: 2026-08-22 19:33:37.738305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28087f9366b3'
down_revision: Union[str, Sequence[str], None] = 'aa751ab79fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('connector_name', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('instance_url', sa.String(), nullable=True),
    sa.Column('auth_mode', sa.String(), nullable=False),
    sa.Column('conflict_policy', sa.String(), nullable=False),
    sa.Column('sync_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_configs_connector_name'), 'integration_configs', ['connector_name'], unique=True)
    op.create_index(op.f('ix_integration_configs_id'), 'integration_configs', ['id'], unique=False)
    op.create_table('integration_failures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('connector_name', sa.String(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('error_class', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('first_failure_at', sa.DateTime(), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_failures_connector_name'), 'integration_failures', ['connector_name'], unique=False)
    op.create_index(op.f('ix_integration_failures_entity_name'), 'integration_failures', ['entity_name'], unique=False)
    op.create_index(op.f('ix_integration_failures_error_class'), 'integration_failures', ['error_class'], unique=False)
    op.create_index(op.f('ix_integration_failures_external_id'), 'integration_failures', ['external_id'], unique=False)
    op.create_index(op.f('ix_integration_failures_id'), 'integration_failures', ['id'], unique=False)
    op.create_index(op.f('ix_integration_failures_last_failure_at'), 'integration_failures', ['last_failure_at'], unique=False)
    op.create_index(op.f('ix_integration_failures_status'), 'integration_failures', ['status'], unique=False)
    op.create_table('sync_states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('connector_name', sa.String(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('last_successful_sync', sa.DateTime(), nullable=True),
    sa.Column('last_attempted_sync', sa.DateTime(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_states_connector_name'), 'sync_states', ['connector_name'], unique=False)
    op.create_index(op.f('ix_sync_states_entity_name'), 'sync_states', ['entity_name'], unique=False)
    op.create_index(op.f('ix_sync_states_id'), 'sync_states', ['id'], unique=False)
    op.create_index(op.f('ix_sync_states_status'), 'sync_states', ['status'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('connector_name', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_connector_name'), 'webhook_events', ['connector_name'], unique=False)
    op.create_index(op.f('ix_webhook_events_entity_id'), 'webhook_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_entity_name'), 'webhook_events', ['entity_name'], unique=False)
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_id'), 'webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_events_idempotency_key'), 'webhook_events', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_webhook_events_received_at'), 'webhook_events', ['received_at'], unique=False)
    op.create_index(op.f('ix_webhook_events_status'), 'webhook_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_status'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_received_at'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_idempotency_key'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_entity_name'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_entity_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_connector_name'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_sync_states_status'), table_name='sync_states')
    op.drop_index(op.f('ix_sync_states_id'), table_name='sync_states')
    op.drop_index(op.f('ix_sync_states_entity_name'), table_name='sync_states')
    op.drop_index(op.f('ix_sync_states_connector_name'), table_name='sync_states')
    op.drop_table('sync_states')
    op.drop_index(op.f('ix_integration_failures_status'), table_name='integration_failures')
    op.drop_index(op.f('ix_integration_failures_last_failure_at'), table_name='integration_failures')
    op.drop_index(op.f('ix_integration_failures_id'), table_name='integration_failures')
    op.drop_index(op.f('ix_integration_failures_external_id'), table_name='integration_failures')
    op.drop_index(op.f('ix_integration_failures_error_class'), table_name='integration_failures')
    op.drop_index(op.f('ix_integration_failures_entity_name'), table_name='integration_failures')
    op.drop_index(op.f('ix_integration_failures_connector_name'), table_name='integration_failures')
    op.drop_table('integration_failures')
    op.drop_index(op.f('ix_integration_configs_id'), table_name='integration_configs')
    op.drop_index(op.f('ix_integration_configs_connector_name'), table_name='integration_configs')
    op.drop_table('integration_configs')
    # ### end Alembic commands ###
